#!/bin/bash -e
#
# S2I assemble script for the 'builder-image' image.
# The 'assemble' script currently only supports binary builds.
#
if [ ! -z ${S2I_DEBUG} ]; then
    echo "turning on assembly debug";
  set -x
fi

